export const categories = [
  "technology",
  "lifestyle",
  "business and entrepreneurship",
  "science",
  "arts and culture",
  "self-improvement",
  "parenting and family",
  "travel",
  "sports and fitness",
  "entertainment",
  "crafts",
  "personal finance",
  "home and gardening",
  "social issues",
  "humor and satire",
  "history and heritage",
  "motivation and inspiration",
  "photography",
];
